### ISSUE TITLE
Failed to compile with recent LLVM 16.0.6

### ISSUE THREAD

**Issue by matclab** [stateafl/stateafl#15]
`cd llvm_mode && make` fails with :+1: 
```
afl-llvm-pass.so.cc:130:8: error: no template named 'map' in namespace 'std'; did you mean 'max'?
````

And after having added `#include <map>`, it fails with:
```
afl-llvm-pass.so.cc:222:31: error: no matching member function for call to 'CreateLoad'
```
New `CreateLoad` functions seems to require 3 arguments.

**Comment by matclab** [comment]
For passing readers, it compiles with clang/llvm 11.
